[package]
name = "sandbox"
version = "0.1.0"
edition = "2021"
authors = ["gtlugo"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
foxy = { path = "../foxy" }